name: flutter_yaml_to_dart
description: Convert YAML file into Dart model automatically
version: 0.0.3
homepage: https://github.com/babakoto/flutter_yaml_to_dart
# repository: https://github.com/my_org/my_repo

executables:
  yaml_dart:
environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.3
  equatable: ^2.0.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

screenshots:
  - description: flutter yaml to dart package logo.
    path: assets/logo.png