class: Product
fields:
  - id: String
  - price: double?
  - description: String?
  - counts: List<int>
  - images: List<String>
    default: []
  - createdAt: DateTime?
    key: "created_at"


toMap: true
fromMap: true
copyWith: true



