class: Product
fields:
  - id: String
  - price: double
  - name: String?
  - isAvailable: bool
  - images: List<String>
    default: "['madagascar','paris','newyork']"
  - max: int?
    default: 0
  - status: enum?
    values: ["active-file", "inactive"]
    default: "active-file"

  - description: String?
  - counts: List<int>
    default: [1,2,3]
  - createdAt: DateTime?
    default: DateTime.now()
    key: "created_at"


toMap: true
fromMap: true
copyWith: true



